# Data Preprocessing

In this notebook we prepare the raw airline dataset for analysis and machine learning.

The preprocessing steps include:

- Loading the raw dataset
- Handling missing values
- Removing cancelled and diverted flights
- Creating the target variable (Delayed)
- Saving the cleaned dataset for further analysis

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")
import gdown

## Load Dataset from Google Drive

The dataset is stored on Google Drive and loaded directly using a shareable download link.

In [2]:
import gdown

file_id = "1czSA9diDpcHBECeKJ-F-aP912lqUumNN"

url = f"https://drive.google.com/uc?id={file_id}"

output_path = r"C:\Users\ASUS\Desktop\Data_Science_Internship\Final_Project\Dataset\DelayedFlights1.csv"

gdown.download(url, output_path, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1czSA9diDpcHBECeKJ-F-aP912lqUumNN
From (redirected): https://drive.google.com/uc?id=1czSA9diDpcHBECeKJ-F-aP912lqUumNN&confirm=t&uuid=afcd5ba7-a152-469e-9364-34095c6a9a6b
To: C:\Users\ASUS\Desktop\Data_Science_Internship\Final_Project\Dataset\DelayedFlights1.csv
100%|██████████| 248M/248M [00:39<00:00, 6.26MB/s]

'C:\\Users\\ASUS\\Desktop\\Data_Science_Internship\\Final_Project\\Dataset\\DelayedFlights1.csv'

In [6]:
df = pd.read_csv("C:\\Users\\ASUS\\Desktop\\Data_Science_Internship\\Final_Project\\Dataset\\DelayedFlights1.csv")

df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

## Dataset Inspection
We inspect the dataset structure, data types, and missing values.

In [7]:
df.shape

(1936758, 30)

In [8]:
df.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [10]:
df.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,3.341651e+06,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,2.066065e+06,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517452e+06,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.242558e+06,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,4.972467e+06,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,7.009727e+06,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

## Remove Unnecessary Columns

The dataset contains an extra column (`Unnamed: 0`) which is not relevant for analysis or model training.  
We remove it to clean the dataset.

In [11]:
df = df.drop(columns=["Unnamed: 0"])
df = df.dropna(subset=["ArrDelay"])

## Missing Value Analysis

Before training machine learning models, we check for missing values in the dataset.

In [12]:
df.isnull().sum().sort_values(ascending=False)

CarrierDelay         680883
LateAircraftDelay    680883
SecurityDelay        680883
NASDelay             680883
WeatherDelay         680883
TailNum                   3
DepTime                   0
CRSArrTime                0
CRSDepTime                0
Month                     0
DayofMonth                0
DayOfWeek                 0
Year                      0
CRSElapsedTime            0
ActualElapsedTime         0
FlightNum                 0
UniqueCarrier             0
ArrTime                   0
AirTime                   0
DepDelay                  0
ArrDelay                  0
TaxiOut                   0
TaxiIn                    0
Distance                  0
Dest                      0
Origin                    0
Diverted                  0
Cancelled                 0
CancellationCode          0
dtype: int64

## Handling Missing Delay Values

Delay-related columns contain missing values because they are only recorded when a delay occurs.
For flights with no delay, these values are filled with 0.

In [13]:
delay_cols = [
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay"
]

df[delay_cols] = df[delay_cols].fillna(0)

## Removing Cancelled or Diverted Flights

Flights that were cancelled or diverted do not contain valid arrival delay information,
so they are removed from the dataset.

In [14]:
df = df[df["Cancelled"] == 0]
df = df[df["Diverted"] == 0]

## Target Variable Creation

Flights delayed by more than 15 minutes are labeled as delayed.

In [15]:
df["Delayed"] = (df["ArrDelay"] > 15).astype(int)
df["Delayed"].value_counts()

Delayed
1    1215012
0     713359
Name: count, dtype: int64

## Reduce Dataset Size

In [16]:
df = df.sample(n=100000, random_state=42)

## Feature Engineering: Extract Departure and Arrival Hour

The scheduled departure and arrival times are stored as integers in HHMM format.
To improve model performance, we extract the **hour of departure and arrival**.

This helps the model learn patterns such as:

- Morning congestion
- Evening peak traffic
- Night flight delays

In [17]:
df["DepHour"] = df["CRSDepTime"] // 100
df["ArrHour"] = df["CRSArrTime"] // 100

## Drop og time cols

In [18]:
df = df.drop(columns=["CRSDepTime", "CRSArrTime"])

## Save Processed Dataset

In [20]:
df.to_csv(r"C:\\Users\\ASUS\\Desktop\\Data_Science_Internship\\Final_Project\\Dataset, index=False")